plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}
android {
    namespace 'com.vrunity.vrapk'
    compileSdk 34
    ndkVersion System.getenv('VRUNITY_NDK_VERSION') ?: '27.3.13750724'
    defaultConfig {
        applicationId 'com.vrunity.vrapk'
        minSdk 29
        targetSdk 34
        versionCode 1790959092
        versionName '1.289'
        ndk { abiFilters 'arm64-v8a' }
    }
    signingConfigs {
        debug {
            storeFile file(System.getenv('RUNNER_TEMP') ? System.getenv('RUNNER_TEMP') + '/.android/debug.keystore' : System.getProperty('user.home') + '/.android/debug.keystore')
        }
    }
    buildTypes {
        release { minifyEnabled false }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    externalNativeBuild {
        cmake {
            path 'src/main/cpp/CMakeLists.txt'
            version System.getenv('VRUNITY_CMAKE_VERSION') ?: '3.31.5'
        }
    }
}
